### PR TITLE
docs: fix typos

### LINKED ISSUE #346: fix : unused imported module and typo grammar
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-dialogflow/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

- unused imported of module ```callback```,```OrderedDict```
- typo comment spelling

#### Environment details

  - OS type and version: linux arch
  - Python version: `python 3.8.10`
  - pip version: `pip 20.0.2`
  - `google-cloud-dialogflow` version: `2.7.0`

#### Steps to reproduce

  1. removed unused import module
  2. fixing code grammar spelling

#### Code example

```python
from typing import Awaitable, Callable, Dict, Optional, Sequence, Tuple, Union
```
to
```python
from typing import Awaitable, Callable, Dict, Optional, Sequence, Tuple
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by slowy07**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-dialogflow/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #346  🦕

### CODE REVIEW

**Review by dandhlee — COMMENTED** [review]
LGTM, @parthea this looks like another set of generated files, could you file a CL for the corresponding changes?

**Comment by slowy07** [comment]
> LGTM, @parthea this looks like another set of generated files, could you file a CL for the corresponding changes?

maybe there is still a writing error or something, would you like to see it again sir? @dandhlee, 
I'm afraid if there are still mistakes in writing or spelling 😂

**Comment by dandhlee** [comment]
@slowy07 I don't see any spelling mistakes based on what you've submitted! :)

**Comment by slowy07** [comment]
> @slowy07 I don't see any spelling mistakes based on what you've submitted! :)

okay thanks sir @dandhlee

**Comment by parthea** [comment]
Created PR https://github.com/googleapis/gapic-generator-python/pull/962 and internal CLs (cl/386724394 and cl/386724394) to fix autogenerated code.

**Review by parthea — APPROVED** [review]
Thanks @slowy07!

**Comment by slowy07** [comment]
> Thanks @slowy07!

your welcome sir @parthea  !

**Pull request merged**
