### PR TITLE
docs: fix typos in UPGRADING.md

### PR DESCRIPTION
**Pull request by reichenbch**
dialogvlow_v2 to dialogflow_v2

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-dialogflow/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Review by busunkim96 — APPROVED** [review]
Thank you!

**Comment by busunkim96** [comment]
@reichenbch Could you review https://github.com/googleapis/python-dialogflow/pull/472/checks?check_run_id=5090689460 and sign the Contributor License Agreement?

**Comment by reichenbch** [comment]
> @reichenbch Could you review https://github.com/googleapis/python-dialogflow/pull/472/checks?check_run_id=5090689460 and sign the Contributor License Agreement?

@busunkim96 Signed the CLA.

**Comment by dandhlee** [comment]
Thank you! Confirmed the CLA has been signed, updating commit header to align with conventional commit style.

**Pull request merged**
